// ─── memo init ───────────────────────────────────────────────────────────────
//
// Scaffolds a new MEMO project with:
//   - memo.config.yaml (extends @memo/medical-modeling-profile)
//   - model/ directory with a starter .sysml file
// ─────────────────────────────────────────────────────────────────────────────

import { resolve } from 'node:path';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import chalk from 'chalk';

export async function initCommand(
    name: string,
    options: { template: string }
): Promise<void> {
    const projectDir = resolve(process.cwd(), name);

    if (existsSync(projectDir)) {
        console.error(chalk.red(`❌ Directory "${name}" already exists.`));
        process.exit(1);
    }

    console.log(chalk.bold(`\n📦 Creating MEMO project: ${name}\n`));

    // Create directory structure
    mkdirSync(projectDir, { recursive: true });
    mkdirSync(resolve(projectDir, 'model'), { recursive: true });

    // Write memo.config.yaml
    const configContent = `# ${name} — MEMO device model
projectName: ${name}
projectType: device

extends: "@memo/medical-modeling-profile"

ontologies:
  - name: memo-ontology-medical
    version: "^0.1.0"
`;

    writeFileSync(resolve(projectDir, 'memo.config.yaml'), configContent);
    console.log(chalk.gray(`  Created memo.config.yaml`));

    // Write starter .sysml file
    const sysmlContent = `// ${name} — SysML v2 Model
// Generated by \`memo init\`

package ${toIdentifier(name)} {
    import MEMO_Ontology_Medical::*;

    // ─── System Definition ──────────────────────────────────────────

    part ${toIdentifier(name)}System : System {
        attribute redefines name = "${name}";
    }

    // ─── Example Requirement ────────────────────────────────────────

    requirement mainRequirement : SystemRequirement {
        attribute redefines title = "Main system requirement";
        doc /* TODO: define your first system requirement */
    }

    // ─── Example Hazard ─────────────────────────────────────────────

    requirement exampleHazard : Hazard {
        attribute redefines title = "Example hazard";
        doc /* TODO: identify hazards per ISO 14971 */
    }
}
`;

    writeFileSync(resolve(projectDir, 'model', `${name}.sysml`), sysmlContent);
    console.log(chalk.gray(`  Created model/${name}.sysml`));

    console.log(chalk.green(`\n✅ Project created at ./${name}`));
    console.log(chalk.gray(`\n  Next steps:`));
    console.log(chalk.gray(`    cd ${name}`));
    console.log(chalk.gray(`    memo dev\n`));
}

function toIdentifier(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_');
}

function toPascalCase(name: string): string {
    return name
        .split(/[-_\s]+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('');
}
