# Irrigation Pump Project — example model with behavior viewpoint
projectName: irrigation-pump
projectType: device

extends: "@memo/medical-modeling-profile"

ontologies:
  - name: "@memo/ontology-medical-arch"
    version: "^0.2.0"
  - name: "@memo/ontology-medical-process"
    version: "^0.2.0"
  - name: "@memo/medical-product-line-profile"
    version: "^0.1.0"

modules:
  - "@memo/ontology-clinical-procedure"
  - "@memo/ontology-clinical-interop"
