// Generated by scripts/generate-notation-registry.mjs from SysML-graphical-bnf.kgbnf. Do not edit.
export const GRAPHICAL_BNF_SOURCE = 'SysML-graphical-bnf.kgbnf' as const;
export const GRAPHICAL_BNF_PRODUCTIONS = [
    "accept-action-node",
    "send-action-node",
    "decision-node",
    "merge-node",
    "fork-node",
    "join-node"
] as const;
