#!/usr/bin/env bash
# sync-roadmap.sh — Pull GitLab issues into local roadmap files
# Usage: pnpm run sync:roadmap
# Requires: glab CLI authenticated to gitlab.com
#
# GitLab is the single source of truth.
# Phase files only list issues that are OPEN in GitLab.
# Closed issues are silently excluded — no stale entries.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROADMAP_DIR="$REPO_DIR/docs/roadmap"
PROJECT="somesh_sandbox/memo"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "🔄 Syncing roadmap from GitLab ($PROJECT)..."

rm -rf "$ROADMAP_DIR"
mkdir -p "$ROADMAP_DIR"

# ── Fetch all open issues ─────────────────────────────────────────────
echo "   Fetching open issues..."
ISSUES_RAW=$(glab issue list -R "$PROJECT" --per-page 200 2>/dev/null || echo "")
TOTAL_OPEN=$(echo "$ISSUES_RAW" | tail -n +3 | grep -c "^#" 2>/dev/null || echo "0")

# Build set of open issue IDs (e.g. "#106")
OPEN_IDS=$(echo "$ISSUES_RAW" | tail -n +3 | awk '{print $1}' | grep "^#")

echo "   Fetching milestones..."
ML_ACTIVE=$(glab milestone list --project "$PROJECT" --per-page 50 --state active 2>/dev/null || echo "None")
ML_CLOSED_COUNT=$(glab milestone list --project "$PROJECT" --per-page 50 --state closed 2>/dev/null | grep -c "^" 2>/dev/null || echo "0")

# ── Helper: emit issue line only if open ──────────────────────────────
# Usage: open_issue "#123" "Description. Scope: S"
open_issue() {
  local id="$1"
  local desc="$2"
  if echo "$OPEN_IDS" | grep -qx "$id"; then
    echo "- **$id** — $desc"
  fi
}

# ── Helper: check if any issues in a list are open ───────────────────
any_open() {
  for id in "$@"; do
    if echo "$OPEN_IDS" | grep -qx "$id"; then
      return 0
    fi
  done
  return 1
}

# ── index.md ──────────────────────────────────────────────────────────
cat > "$ROADMAP_DIR/index.md" << EOF
# Roadmap Index

> **Source of truth:** GitLab issues & milestones (\`somesh_sandbox/memo\`)
> Auto-generated by \`pnpm run sync:roadmap\` — do not edit manually.
> Synced: $TIMESTAMP | Open issues: $TOTAL_OPEN | Closed milestones: $ML_CLOSED_COUNT

## Phases (read only the phase you need)

| Phase | File | Priority | Focus |
|-------|------|----------|-------|
| 1 | [phase-1.md](phase-1.md) | **P0** | Ontology cleanup (extract ROS/RabbitMQ, collapse types, simplify) |
| A | [phase-a.md](phase-a.md) | P0 | Critical bug fixes |
| B | [phase-b.md](phase-b.md) | P1 | UX foundation |
| C | [phase-c.md](phase-c.md) | P1 | Visual ontology viewer |
| D | [phase-d.md](phase-d.md) | P2 | Diagrams & views |
| E | [phase-e.md](phase-e.md) | P2 | DHF improvements |
| F | [phase-f.md](phase-f.md) | P2 | Model & scenarios |
| G | [phase-g.md](phase-g.md) | P3 | Examples (GPCA reference model, starter templates) |
| H | [phase-h.md](phase-h.md) | Nice-to-have | Cloud & collaboration |
| I | [phase-i.md](phase-i.md) | Nice-to-have | Domain packages |
| J | [phase-j.md](phase-j.md) | P2 | Import — CLI formats + UI element/relationship creation |
| K | [phase-k.md](phase-k.md) | P3 | Docs & manuals |

Also: [bugs.md](bugs.md) — all open bugs

## Active GitLab Milestones

$ML_ACTIVE

## Execution Order

1 → A → B → C → D/E/F/J (parallel) → G/K → H/I (deferred)
EOF

# ── bugs.md ───────────────────────────────────────────────────────────
{
  echo "# Open Bugs"
  echo ""
  echo "> Source: GitLab open issues with bug/fix labels"
  echo ""
  echo "| ID | Title | Labels | Created |"
  echo "|----|-------|--------|---------|"
  echo "$ISSUES_RAW" | tail -n +3 | grep -iE "bug|type::fix" | while IFS=$'\t' read -r id title labels created rest; do
    [ -z "$id" ] && continue
    echo "| $id | $title | $labels | $created |"
  done
} > "$ROADMAP_DIR/bugs.md"

# ══════════════════════════════════════════════════════════════════════
# Phase files — only open issues are listed
# ══════════════════════════════════════════════════════════════════════

# ── Phase 1 — Ontology Cleanup ────────────────────────────────────────
{
  echo "# Phase 1 — Ontology Cleanup (P0)"
  echo ""
  echo "Simplify the monolithic ontology. Extract technology-specific defs, collapse over-split types, move niche concepts to extensions."
  echo "Target: ~140 core + ~150 medical = ~290 total (down from 375)."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#97"  "Extract ROS definitions into @memo/ontology-platform-robotics. Scope: M"
  open_issue "#98"  "Extract RabbitMQ definitions into @memo/ontology-platform-messaging. Scope: S"
  open_issue "#99"  "Collapse IEC 62304 software lifecycle types (28 → ~15). Scope: M"
  open_issue "#100" "Collapse FTA/FMEA risk analysis types (14 → ~8). Scope: M"
  open_issue "#101" "Move clinical/pharma concepts to @memo/ontology-clinical. Scope: M"
  open_issue "#102" "Move terminology import defs to @memo/ontology-clinical-interop. Scope: S"
  open_issue "#103" "Collapse privacy/GDPR types (16 → ~6). Scope: S"
  open_issue "#104" "Move product-line concepts to @memo/medical-product-line-profile. Scope: S"
  open_issue "#105" "Collapse design-control validation subtypes (13 → ~10). Scope: S"
  open_issue "#91"  "Fix misclassified behavioral elements (UseCase, MissionPhase). Scope: M"
  open_issue "#93"  "Simplify granular relationships and redundant elements. Scope: M"
  open_issue "#111" "Validate GPCA model against simplified ontology. Scope: M"
} > "$ROADMAP_DIR/phase-1.md"

# ── Phase A — Critical Bug Fixes ─────────────────────────────────────
{
  echo "# Phase A — Critical Bug Fixes (P0)"
  echo ""
  echo "Fix issues that make the app look broken or unusable."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#81" "Product title shows 'MEMO Workbench' instead of 'MEMO Architect'. Scope: S"
  open_issue "#82" "Legacy 'CoSMA' terminology still in project. Scope: S"
  open_issue "#83" "Text too small, contrast too low in side panels. Scope: S"
  open_issue "#84" "Clicking item should show full-page properties. Scope: M"
  open_issue "#85" "Full model overview diagram is an unconsumable model dump. Scope: M"
  open_issue "#86" "Dual sidebars in Ontology mode. Scope: M"
  open_issue "#91" "Misclassification of behavioral elements (UseCase, MissionPhase). Scope: M"
  open_issue "#93" "Simplify granular relationships and redundant elements. Scope: M"
} > "$ROADMAP_DIR/phase-a.md"

# ── Phase B — UX Foundation ───────────────────────────────────────────
{
  echo "# Phase B — UX Foundation (P1)"
  echo ""
  echo "Navigation, layout, and interaction fundamentals."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#62" "Redesign welcome screen — center background, improve onboarding. Scope: M"
  open_issue "#66" "Allow creating subfolders under element types and moving elements. Scope: M"
  open_issue "#69" "'Others' category too granular — use attributes instead of separate types. Scope: M"
  open_issue "#70" "Bottom bar should behave like VS Code Problems panel. Scope: M"
  open_issue "#74" "ActionFlow should not be a top-level nav item — move under Diagrams. Scope: M"
  open_issue "#75" "Quick-browse items should be clickable and navigate to element. Scope: S"
} > "$ROADMAP_DIR/phase-b.md"

# ── Phase C — Visual Ontology Viewer ─────────────────────────────────
{
  echo "# Phase C — Visual Ontology Viewer (P1)"
  echo ""
  echo "Replace the flat list ontology viewer with a visual graph grouped by architecture layer/domain."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#7"  "Build visual ontology editor in web app. Scope: L"
  open_issue "#80" "Ontology viewer: grouped by type with relationships visualized, collapsible groups. Scope: L"
  open_issue "#89" "Ontology restructuring & pluggable ontology manager. Scope: L"
  open_issue "#92" "Finalize modular ontology registration. Scope: M"
} > "$ROADMAP_DIR/phase-c.md"

# ── Phase D — Diagrams & Views ────────────────────────────────────────
{
  echo "# Phase D — Diagrams & Views (P2)"
  echo ""
  echo "Auto-view organization and user-created diagrams with SysML editing."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#71" "'Auto' views should be a folder with individual diagrams, not one model dump. Scope: M"
  open_issue "#72" "Support user-created diagrams with SysML v2 editing — visual, text, side-by-side. Scope: L"
} > "$ROADMAP_DIR/phase-d.md"

# ── Phase E — DHF Improvements ───────────────────────────────────────
{
  echo "# Phase E — DHF Improvements (P2)"
  echo ""
  echo "Markdown-first DHF authoring workbench with explorer, template picker, and per-document editor."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#76"  "DHF should use an explorer-type interface. Scope: M"
  open_issue "#77"  "Add a template editor for DHF documents. Scope: L"
  open_issue "#78"  "DHF dashboard should be the homepage of the DHF tab. Scope: M"
  open_issue "#121" "DHF Workbench: Markdown-first authoring with community template registry. Scope: L"
} > "$ROADMAP_DIR/phase-e.md"

# ── Phase F — Model & Scenarios ──────────────────────────────────────
{
  echo "# Phase F — Model & Scenarios (P2)"
  echo ""
  echo "Scenarios editor and model diff."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#73" "Remove 'Sets' and replace with a Scenarios editor. Scope: M"
  open_issue "#79" "Define and document how model diff works. Scope: L"
} > "$ROADMAP_DIR/phase-f.md"

# ── Phase G — Examples ───────────────────────────────────────────────
{
  echo "# Phase G — Examples (P3)"
  echo ""
  echo "GPCA as the single strong reference model. Infusion-pump trimmed to minimal starter template."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#106" "Remove irrigation-pump example (industrial domain noise). Scope: S"
  open_issue "#107" "Trim infusion-pump to minimal starter template (~100 lines). Scope: S"
  open_issue "#87"  "Make GPCA the default in \`memo init\`. Scope: M"
  open_issue "#108" "Add CriSys source references to GPCA model elements. Scope: M"
  open_issue "#110" "Complete GPCA clinical/usability model (75% → 90%). Scope: M"
  open_issue "#109" "Complete GPCA cybersecurity model (70% → 90%). Scope: M"
} > "$ROADMAP_DIR/phase-g.md"

# ── Phase H — Cloud & Collaboration ──────────────────────────────────
{
  echo "# Phase H — Cloud & Collaboration (Nice-to-have)"
  echo ""
  echo "Deferred until core features are solid."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#58" "Build cloud-hosted version with user accounts. Scope: L"
  open_issue "#59" "Multi-user collaboration with conflict resolution. Scope: L"
  open_issue "#60" "Element-level comments and discussion threads. Scope: M"
} > "$ROADMAP_DIR/phase-h.md"

# ── Phase I — Domain Packages ─────────────────────────────────────────
{
  echo "# Phase I — Domain Packages (Nice-to-have)"
  echo ""
  echo "Deferred until core features are solid."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#56" "Create @memo/automotive package (ISO 26262). Scope: L"
  open_issue "#57" "Create @memo/aerospace package (DO-178C). Scope: L"
} > "$ROADMAP_DIR/phase-i.md"

# ── Phase J — Import ─────────────────────────────────────────────────
{
  echo "# Phase J — Import (P2)"
  echo ""
  echo "Import elements and relationships into MEMO — both from the CLI (AADL, CSV, EA, Cameo) and directly from the web UI."
  echo ""
  echo "## Open Issues"
  echo ""
  echo "### CLI Import Formats"
  open_issue "#88"  "SysML v2 to AADL (and vice-versa) import/export. Scope: L"
  echo ""
  echo "### UI-Based Importing"
  open_issue "#122" "Create and edit elements from the UI (kind picker, attributes, doc field). Scope: M"
  open_issue "#123" "Create and edit relationships between elements from the UI. Scope: M"
  open_issue "#124" "Bulk import elements from CSV or paste table in UI. Scope: M"
} > "$ROADMAP_DIR/phase-j.md"

# ── Phase K — Docs & Manuals ──────────────────────────────────────────
{
  echo "# Phase K — Docs & Manuals (P3)"
  echo ""
  echo "User manual, developer manual, hidden feature docs, documentation site restructure."
  echo ""
  echo "## Open Issues"
  echo ""
  open_issue "#90" "Restructure documentation site (users vs developers). Scope: M"
  open_issue "#94" "User manual: all CLI commands, config options, and workflows. Scope: L"
  open_issue "#95" "Developer manual: architecture, contributing, extension development. Scope: L"
  open_issue "#96" "Document hidden features: LLM commands, env vars, import formats, config options. Scope: S"
} > "$ROADMAP_DIR/phase-k.md"

echo "✅ Roadmap synced to $ROADMAP_DIR/"
echo "   $TOTAL_OPEN open issues — closed issues excluded from all phase files"
echo ""
echo "   💡 To read only what you need:"
echo "      cat docs/roadmap/index.md        # ~30 lines, always start here"
echo "      cat docs/roadmap/phase-a.md      # only when working on Phase A"
