# Infusion Pump Project — example device model using @memo/medical-modeling-profile config
projectName: infusion-pump
projectType: device

extends: "@memo/medical-modeling-profile"

ontologies:
  - name: memo-ontology-medical
    version: "^0.1.0"
  - name: "@memo/ontology-platform-robotics"
    version: "^0.1.0"
  - name: "@memo/ontology-platform-messaging"
    version: "^0.1.0"
